services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file: '.env'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_DB}
    depends_on:
      - db
    networks:
      - my_network
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    networks:
      - my_network

networks:
  my_network:
    name: my_network
    driver: bridge
